export class ProcessTempSave{
    inspecTemp: InspecTemp;
    inspecCnfrmnIssu: InspecCnfrmnIssu;
    userId: string;
    constructor(){
        this.inspecTemp = new InspecTemp();
        this.inspecCnfrmnIssu = new InspecCnfrmnIssu();
        this.userId = null;
    }
  }
export class InspecTemp{
    athrzProcessSttusCode: string;
    athrzSn: number;
    processPrarnDe: Date;
    insttSn: number;
    athrzReqstNo: number;
    athrzRceptNo: string;
    ktcBrffcCode: string;
    proprod: number;
    entrpsSn: number;
    entrpsNm: string;
    rprsntvNm: string;
    bizrno: string;
    bplcAdresSeCode: string;
    bplcZip: string;
    bplcBassAdres: string;
    bplcDetailAdres: string;
    bplcTelno: string;
    bplcFxnum: string;
    fctryAdresSeZip: string;
    fctryZip: string;
    fctryBassAdres: string;
    fctryDetailAdres: string;
    fctryTelno: string;
    fctryFxnum: string;
    vesslNoMarkSeCode: string;
    bsrpDeCtDaycnt: number;
    bsrpNmprCo: number;
    bsrpDeCtAmount: number;
    bsrpStayngCtDaycnt: number;
    bsrpStayngCtAmount: number;
    btrpsSm: number;
    tnAthrzfeeAmount: number;
    postFee: number;
    eqpRntfee: number;
    athrzCnfrmnOutptAmount: number;
    etcamount: number;
    subsum: number;
    vat: number;
    totalSmAm: number;
    payAt: string;
    feePayDe: string;
    feePayCnfrmrId: string;
    feePayCnfrmrNm: string;
    feePayCnfrmrDeptNm: string;
    athrzReqstCn: string;
    athrzProcessCn: string;
    applcntId: string;
    applcntNm: string;
    applcntTelno: string;
    applcntMbtlnum: string;
    applcntEmailAdres: string;
    rm: string;
    rceptDe: string;
    rceptChargerId: string;
    rceptChargerNm: string;
    rceptChargerDeptNm: string;
    rceptConfmerId: string;
    rceptConfmerNm: string;
    rceptConfmerDeptNm: string;
    athrzChargerId: string;
    athrzChargerNm: string;
    athrzChargerDeptNm: string;
    athrzChargerTelno: string;
    lastConfmDe: string;
    athrzRspnberId: string;
    athrzRspnberNm: string;
    athrzRspnberDeptNm: string;
    athrzDetailSn: number;
    mrnrSeCode: string;


    athrzExpDe1: number;
    athrzExpDe2: number;
    fomConfmConfmNo: string;
    stndrdNm: string;
    athrzSeCode: string;
    reqstQy: number;
    reqstQy2: string;
    psexamQy: number;
    dsqlfcQy: number;
    athrzBgnDe: string;
    athrzEndDe: string;
    untpc: number;
    amount: number;
    athrzMthCode: string;
    athrzAreaAdresSeCode: string;
    athrzAreaZip: string;
    athrzAreaBassAdres: string;
    athrzAreaTaxAdres: string;
    athrzAreaTelno: string;
    mesurProofBsshAt: string;
    athrzHopeDe: Date;
    athrzExpDe: string;
    athrzAllAt: string;
    mode: string;
    constructor(){
        this.athrzProcessSttusCode = null;
        this.athrzSn = 0;
        this.processPrarnDe = null;
        this.insttSn = 0;
        this.athrzReqstNo = 0;
        this.athrzRceptNo = null;
        this.ktcBrffcCode = null;
        this.proprod = 0;
        this.entrpsSn = 0;
        this.entrpsNm = null;
        this.rprsntvNm = null;
        this.bizrno = null;
        this.bplcAdresSeCode = null;
        this.bplcZip = null;
        this.bplcBassAdres = null;
        this.bplcDetailAdres = null;
        this.bplcTelno = null;
        this.bplcFxnum = null;
        this.fctryAdresSeZip = null;
        this.fctryZip = null;
        this.fctryBassAdres = null;
        this.fctryDetailAdres = null;
        this.fctryTelno = null;
        this.fctryFxnum = null;
        this.vesslNoMarkSeCode = null;
        this.bsrpDeCtDaycnt = 0;
        this.bsrpNmprCo = 0;
        this.bsrpDeCtAmount = 0;
        this.bsrpStayngCtDaycnt = 0;
        this.bsrpStayngCtAmount = 0;
        this.btrpsSm = 0;
        this.tnAthrzfeeAmount = 0;
        this.postFee = 0;
        this.eqpRntfee = 0;
        this.athrzCnfrmnOutptAmount = 0;
        this.etcamount = 0;
        this.subsum = 0;
        this.vat = 0;
        this.totalSmAm = 0;
        this.payAt = null;
        this.feePayDe = null;
        this.feePayCnfrmrId = null;
        this.feePayCnfrmrNm = null;
        this.feePayCnfrmrDeptNm = null;
        this.athrzReqstCn = null;
        this.athrzProcessCn = null;
        this.applcntId = null;
        this.applcntNm = null;
        this.applcntTelno = null;
        this.applcntMbtlnum = null;
        this.applcntEmailAdres = null;
        this.rm = null;
        this.rceptDe = null;
        this.rceptChargerId = null;
        this.rceptChargerNm = null;
        this.rceptChargerDeptNm = null;
        this.rceptConfmerId = null;
        this.rceptConfmerNm = null;
        this.rceptConfmerDeptNm = null;
        this.athrzChargerId = null;
        this.athrzChargerNm = null;
        this.athrzChargerDeptNm = null;
        this.athrzChargerTelno = null;
        this.lastConfmDe = null;
        this.athrzRspnberId = null;
        this.athrzRspnberNm = null;
        this.athrzRspnberDeptNm = null;
        this.athrzDetailSn = 0;
        this.mrnrSeCode = null;

        this.athrzExpDe1 = 0;
        this.athrzExpDe2 = 0;
        this.fomConfmConfmNo = null;
        this.stndrdNm = null;
        this.athrzSeCode = null;
        this.reqstQy = 0;
        this.reqstQy2 = null;
        this.psexamQy = 0;
        this.dsqlfcQy = 0;
        this.athrzBgnDe = null;
        this.athrzEndDe = null;
        this.untpc = 0;
        this.amount = 0;
        this.athrzMthCode = null;
        this.athrzAreaAdresSeCode = null;
        this.athrzAreaZip = null;
        this.athrzAreaBassAdres = null;
        this.athrzAreaTaxAdres = null;
        this.athrzAreaTelno = null;
        this.mesurProofBsshAt = null;
        this.athrzHopeDe = null;
        this.athrzExpDe = null;
        this.athrzAllAt = null;
        this.mode = null;
    }
}
export class InspecCnfrmnIssu{
    athrzSn: number;
    constructor(){
        this.athrzSn = 0;
    }
}
