export class TestInfoSave{
    inspectionT: InspectionSave;
    inspectionCnfrmnIssuT: CnfrmnIssuTSave;
    userId: string;
    constructor(){
        this.inspectionT = new InspectionSave();
        this.inspectionCnfrmnIssuT = new CnfrmnIssuTSave();
        this.userId = null;
    }
}

export class InspectionSave{
    athrzProcessSttusCode: string;
    dbInputAt: string;
    athrzExpDe1: number;
    athrzExpDe2: number;
    athrzSn: number;
    processPrarnDe: string;
    athrzReqstNo: number;
    athrzRceptNo: string;
    ktcBrffcCode: string;
    proprod: number;
    entrpsSn: number;
    entrpsNm: string;
    rprsntvNm: string;
    entrpsSeNm: string;
    bizrno: string;
    bplcAdresSeCode: string;
    bplcZip: string;
    bplcBassAdres: string;
    bplcDetailAdres: string;
    bplcTelno: string;
    bplcFxnum: string;
    fctryAdresSeZip: string;
    fctryZip: string;
    fctryBassAdres: string;
    fctryDetailAdres: string;
    fctryTelno: string;
    fctryFxnum: string;
    vesslNoMarkSeCode: string;
    bsrpTrnsportCt: number;
    bsrpDeCtDaycnt: number;
    bsrpNmprCo: number;
    bsrpDeCtAmount: number;
    bsrpStayngCtDaycnt: number;
    bsrpStayngCtAmount: number;
    btrpsSm: number;
    tnAthrzfeeAmount: number;
    postFee: number;
    eqpRntfee: number;
    athrzCnfrmnOutptAmount: number;
    etcamount: number;
    subsum: number;
    vat: number;
    totalSmAm: number;
    payAt: string;
    feePayDe: string;
    feePayCnfrmrId: string;
    feePayCnfrmrNm: string;
    feePayCnfrmrDeptNm: string;
    athrzReqstCn: string;
    athrzProcessCn: string;
    rqstDt: Date;
    applcntId: string;
    applcntNm: string;
    applcntTelno: string;
    applcntMbtlnum: string;
    applcntEmailAdres: string;
    rm: string;
    rceptDe: Date;
    rceptChargerId: string;
    rceptChargerNm: string;
    rceptChargerDeptNm: string;
    rceptConfmDe: Date;
    rceptConfmerId: string;
    rceptConfmerNm: string;
    rceptConfmerDeptNm: string;
    athrzChargerId: string;
    athrzChargerNm: string;
    athrzChargerDeptNm: string;
    athrzChargerTelno: string;
    lastConfmDe: Date;
    athrzRspnberId: string;
    athrzRspnberNm: string;
    athrzRspnberDeptNm: string;
    athrzDetailSn: number;
    mrnrSeCode: string;
    fomConfmConfmNo: string;
    stndrdNm: string;
    athrzSeCode: string;
    reqstQy: number;
    reqstQy2: string;
    psexamQy: number;
    dsqlfcQy: number;
    athrzBgnDe: string;
    athrzEndDe: string;
    untpc: number;
    amount: number;
    athrzMthCode: string;
    athrzAreaAdresSeCode: string;
    athrzAreaZip: string;
    athrzAreaBassAdres: string;
    athrzAreaTaxAdres: string;
    athrzAreaTelno: string;
    mesurProofBsshAt: string;
    athrzHopeDe: string;
    athrzExpDe: string;
    athrzAllAt: string;
    mode: string;
    hAthrzFee: string;
    athrzEndDeObject: string[];
    athrzBngDeObject: string[];
    athrzDetailSnObject: string[];
    beforeAthrzProcessSttusCode: string;
    constructor(){
        this.athrzProcessSttusCode = null;
        this.dbInputAt = null;
        this.athrzExpDe1 = 0;
        this.athrzExpDe2 = 0;
        this.athrzSn = 0;
        this.processPrarnDe = null;
        this.athrzReqstNo = 0;
        this.athrzRceptNo = null;
        this.ktcBrffcCode = null;
        this.proprod = 0;
        this.entrpsSn = 0;
        this.entrpsNm = null;
        this.rprsntvNm = null;
        this.entrpsSeNm = null;
        this.bizrno = null;
        this.bplcAdresSeCode = null;
        this.bplcZip = null;
        this.bplcBassAdres = null;
        this.bplcDetailAdres = null;
        this.bplcTelno = null;
        this.bplcFxnum = null;
        this.fctryAdresSeZip = null;
        this.fctryZip = null;
        this.fctryBassAdres = null;
        this.fctryDetailAdres = null;
        this.fctryTelno = null;
        this.fctryFxnum = null;
        this.vesslNoMarkSeCode = null;
        this.bsrpTrnsportCt = 0;
        this.bsrpDeCtDaycnt = 0;
        this.bsrpNmprCo = 0;
        this.bsrpDeCtAmount = 0;
        this.bsrpStayngCtDaycnt = 0;
        this.bsrpStayngCtAmount = 0;
        this.btrpsSm = 0;
        this.tnAthrzfeeAmount = 0;
        this.postFee = 0;
        this.eqpRntfee = 0;
        this.athrzCnfrmnOutptAmount = 0;
        this.etcamount = 0;
        this.subsum = 0;
        this.vat = 0;
        this.totalSmAm = 0;
        this.payAt = null;
        this.feePayDe = null;
        this.feePayCnfrmrId = null;
        this.feePayCnfrmrNm = null;
        this.feePayCnfrmrDeptNm = null;
        this.athrzReqstCn = null;
        this.athrzProcessCn = null;
        this.rqstDt = null;
        this.applcntId = null;
        this.applcntNm = null;
        this.applcntTelno = null;
        this.applcntMbtlnum = null;
        this.applcntEmailAdres = null;
        this.rm = null;
        this.rceptDe = null;
        this.rceptChargerId = null;
        this.rceptChargerNm = null;
        this.rceptChargerDeptNm = null;
        this.rceptConfmDe = null;
        this.rceptConfmerId = null;
        this.rceptConfmerNm = null;
        this.rceptConfmerDeptNm = null;
        this.athrzChargerId = null;
        this.athrzChargerNm = null;
        this.athrzChargerDeptNm = null;
        this.athrzChargerTelno = null;
        this.lastConfmDe = null;
        this.athrzRspnberId = null;
        this.athrzRspnberNm = null;
        this.athrzRspnberDeptNm = null;
        this.athrzDetailSn = 0;
        this.mrnrSeCode = null;
        this.fomConfmConfmNo = null;
        this.stndrdNm = null;
        this.athrzSeCode = null;
        this.reqstQy = 0;
        this.reqstQy2 = null;
        this.psexamQy = 0;
        this.dsqlfcQy = 0;
        this.athrzBgnDe = null;
        this.athrzEndDe = null;
        this.untpc = 0;
        this.amount = 0;
        this.athrzMthCode = null;
        this.athrzAreaAdresSeCode = null;
        this.athrzAreaZip = null;
        this.athrzAreaBassAdres = null;
        this.athrzAreaTaxAdres = null;
        this.athrzAreaTelno = null;
        this.mesurProofBsshAt = null;
        this.athrzHopeDe = null;
        this.athrzExpDe = null;
        this.athrzAllAt = null;
        this.mode = null;
        this.hAthrzFee = null;
        this.athrzEndDeObject = [];
        this.athrzBngDeObject = [];
        this.athrzDetailSnObject = [];
        this.beforeAthrzProcessSttusCode = null;
    }
}

export class CnfrmnIssuTSave{
    athrzSn: number;
    athrzCnfrmnIssuSn: number;
    issuReqstNbfps: number;
    issuOutptNbfps: number;
    issuFeeAmount: number;
    issuPrposCn: string;
    outptIndictSeCode: string;
    outptIndictSeCodeName: string;
    athrzCnfrmnIssuDetailSn: number;
    athrzIssuNo: string;
    athrzAtchmnflSn: number;
    userId: string;
    ktcChargerId: string;
    ktcChargerNm: string;
    ktcChargerDeptNm: string;
    outptAt: string;
    confmnIssuObject: string[];
    athrzDetailSn: number;
    issuProgrsSttus: string;
    athrzAtchmnflCours: string;
    athrzAtchmnflNm: string;
    athrzProcessSttusCode: string;
    rgsDe: string;
    constructor(){
        this.athrzSn = 0;
        this.athrzCnfrmnIssuSn = 0;
        this.issuReqstNbfps = 0;
        this.issuOutptNbfps = 0;
        this.issuFeeAmount = 0;
        this.issuPrposCn = null;
        this.outptIndictSeCode = null;
        this.outptIndictSeCodeName = null;
        this.athrzCnfrmnIssuDetailSn = 0;
        this.athrzIssuNo = null;
        this.athrzAtchmnflSn = 0;
        this.userId = null;
        this.ktcChargerId = null;
        this.ktcChargerNm = null;
        this.ktcChargerDeptNm = null;
        this.outptAt = null;
        this.confmnIssuObject = [];
        this.athrzDetailSn = 0;
        this.issuProgrsSttus = null;
        this.athrzAtchmnflCours = null;
        this.athrzAtchmnflNm = null;
        this.athrzProcessSttusCode = null;
        this.rgsDe = null;
    }
}
